' Developer Express Code Central Example:
' How to show images in a column filter drop-down window
' 
' You can determine your custom column filter drop-down window via the
' GridColumn.CustomColumnFilterPopupTemplate property
' (ms-help://DevExpress.NETv11.2/DevExpress.Wpf/DevExpressXpfGridColumnBase_CustomColumnFilterPopupTemplatetopic.htm).
' In this case, the GridColumn.FilterPopupMode property
' (ms-help://DevExpress.NETv11.2/DevExpress.Wpf/DevExpressXpfGridColumnBase_FilterPopupModetopic.htm)
' should be set to Custom. Simply place ListBoxEdit within DataTemplate and
' override its ItemTemplate property, so it is possible to show an image along
' with a text for every item.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E3941
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace Default_MVVM.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(Default_MVVM.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Default_MVVM.Properties.Resources).Assembly)
                    Default_MVVM.Properties.Resources.resourceMan = temp
                End If

                Return Default_MVVM.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return Default_MVVM.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                Default_MVVM.Properties.Resources.resourceCulture = value
            End Set
        End Property

        Friend Shared ReadOnly Property _1 As System.Drawing.Bitmap
            Get
                Dim obj As Object = Default_MVVM.Properties.Resources.ResourceManager.GetObject("_1", Default_MVVM.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property _2 As System.Drawing.Bitmap
            Get
                Dim obj As Object = Default_MVVM.Properties.Resources.ResourceManager.GetObject("_2", Default_MVVM.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property _3 As System.Drawing.Bitmap
            Get
                Dim obj As Object = Default_MVVM.Properties.Resources.ResourceManager.GetObject("_3", Default_MVVM.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property _4 As System.Drawing.Bitmap
            Get
                Dim obj As Object = Default_MVVM.Properties.Resources.ResourceManager.GetObject("_4", Default_MVVM.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property _5 As System.Drawing.Bitmap
            Get
                Dim obj As Object = Default_MVVM.Properties.Resources.ResourceManager.GetObject("_5", Default_MVVM.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property _6 As System.Drawing.Bitmap
            Get
                Dim obj As Object = Default_MVVM.Properties.Resources.ResourceManager.GetObject("_6", Default_MVVM.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property _7 As System.Drawing.Bitmap
            Get
                Dim obj As Object = Default_MVVM.Properties.Resources.ResourceManager.GetObject("_7", Default_MVVM.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
